import bcrypt

from fastapi import APIRouter, HTTPException, Response, Depends
from pydantic import BaseModel

from db import models
from auth.jwt_handler import create_access_token
from auth.dependencies import get_current_user
from auth.security import (
    set_auth_cookie,
    clear_auth_cookie,
)

router = APIRouter(
    prefix="/auth",
    tags=["Authentication"],
)


# ==========================================================
# Request Models
# ==========================================================

class SignupRequest(BaseModel):
    username: str
    email: str
    password: str


class LoginRequest(BaseModel):
    email: str
    password: str


# ==========================================================
# Signup
# ==========================================================

@router.post("/signup")
async def signup(body: SignupRequest):
    """
    Create a new user account.

    Notes:
    - API key is still generated by create_user()
      for future programmatic access.
    - User is NOT logged in automatically.
    """

    existing_email = models.get_user_by_email(body.email)

    if existing_email:
        raise HTTPException(
            status_code=400,
            detail="Email already registered",
        )

    existing_username = models.get_user_by_username(body.username)

    if existing_username:
        raise HTTPException(
            status_code=400,
            detail="Username already taken",
        )

    password_hash = bcrypt.hashpw(
        body.password.encode(),
        bcrypt.gensalt(),
    ).decode()

    user = models.create_user(
        username=body.username,
        email=body.email,
        password_hash=password_hash,
    )

    return {
        "message": "Account created successfully",
        "user": {
            "id": user["id"],
            "username": user["username"],
            "email": user["email"],
        },
    }


# ==========================================================
# Login
# ==========================================================

@router.post("/login")
async def login(body: LoginRequest, response: Response):
    """
    Authenticate user and issue JWT cookie.
    """
    print("===== LOGIN ENDPOINT HIT =====", flush=True)
    user = models.get_user_by_email(body.email)

    if not user:
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password",
        )

    if not user.get("password_hash"):
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password",
        )

    valid_password = bcrypt.checkpw(
        body.password.encode(),
        user["password_hash"].encode(),
    )

    if not valid_password:
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password",
        )

    access_token = create_access_token(user)

    set_auth_cookie(
        response=response,
        token=access_token,
    )
    print("Cookie should be set")   
    return {
        "message": "Login successful",
        "user": {
            "id": user["id"],
            "username": user["username"],
            "email": user["email"],
        },
    }


# ==========================================================
# Logout
# ==========================================================

@router.post("/logout")
async def logout(response: Response):
    """
    Clear authentication cookie.
    """

    clear_auth_cookie(response)

    return {
        "message": "Logged out successfully",
    }


# ==========================================================
# Current User
# ==========================================================

@router.get("/me")
async def me(
    current_user: dict = Depends(get_current_user),
):
    return {
        "user": {
            "id": current_user["id"],
            "username": current_user["username"],
            "email": current_user["email"],
            "api_key": current_user["api_key"],
            "created_at": current_user["created_at"],
        }
    }

# ==========================================================
# Regenerate API Key
# ==========================================================

@router.post("/regenerate-api-key")
async def regenerate_api_key(
    current_user: dict = Depends(get_current_user),
):
    """
    Regenerate the user's API key.

    This endpoint is intended for users who want to revoke
    an existing API key and create a new one for external
    integrations (CLI, scripts, webhooks, etc.).
    """

    new_api_key = models.regenerate_api_key(current_user["id"])

    return {
        "message": "API key regenerated successfully",
        "api_key": new_api_key,
    }


# ==========================================================
# Validate Session
# ==========================================================

@router.get("/validate-session")
async def validate_session(
    current_user: dict = Depends(get_current_user),
):
    """
    Lightweight endpoint used by the frontend to verify
    that the JWT cookie is still valid.

    Useful during initial page load or app refresh.
    """

    return {
        "authenticated": True,
        "user": {
            "id": current_user["id"],
            "username": current_user["username"],
            "email": current_user["email"],
        },
    }